### ISSUE TITLE
global.json not found

### ISSUE THREAD

**Issue by JFChi** [clinicalml/TabLLM#2]
Hi there,

It seems that your code miss a json file `global.json`. Could you please upload it? Thanks

```
TabLLM/t-few/src/utils/Config.py", line 118, in __init__
    self.update_kwargs(json.load(open(filename)), eval=False)
FileNotFoundError: [Errno 2] No such file or directory 'TabLLM/t-few/configs/global.json'
```

**Comment by Eason-Qin** [comment]
Same problem.

**Comment by stefanhgm** [comment]
Thanks for your interest in using TabLLM! Unfortunately, I currently don’t have access to my computer. I will come back to you on the 11th of April. Sorry for the delay.

In the meantime you might try to use the global.json file from the t-few repo. We based our global.json config on theirs.

Best,
Stefan

**Comment by stefanhgm** [comment]
Hi @JFChi and @Eason-Qin ,

I added the folder `t-few/configs` to the project now that contains all used json configs. As I already mentioned, these configs are taken from the [t-few project](https://github.com/r-three/t-few/tree/master/configs).

Hope that helps!
