### ISSUE TITLE
How can the trained model be used to make predictions on unlabeled data?

### ISSUE THREAD

**Issue by lpy1207** [clinicalml/TabLLM#25]
Hello, thank you very much for your work. How can the trained model be used to make predictions on unlabeled data?

**Comment by stefanhgm** [comment]
Hello @lpy1207,

thanks for using TabLLM!

Basically, the zero-shot results are predictions without training data, so yes this would be possible. Please follow the readme and use the settings for zero-shot in the run script. You can also find some more details about zero-shot experiments here: [Large Language Model Capabilities in Perioperative Risk Prediction and Prognostication](https://github.com/clinicalml/TabLLM/issues/21)

I hope that help!
