### ISSUE TITLE
Confusion about the implementation of “Text-Template” serialization

### ISSUE THREAD

**Issue by yitongshang2021** [clinicalml/TabLLM#27]
Hi, @stefanhgm. Thank you for your perfect work. I have an interesting question that has been puzzling me. How is the Serialization method in your article [Text Template: An textual enumeration of all featuresas “The column name is value.”] implemented? Manually or in code?

**Comment by stefanhgm** [comment]
Hi @yitongshang2021 ,

Thanks you for using TabLLM and for your kind words.

You can find the serializations here: https://github.com/clinicalml/TabLLM/blob/71f6647c523aa6fd35df94ad76207c4377248c49/helper/external_datasets_variables.py#L481

E.g. for the `income` dataset, see `template_income` for the text serialization and `template_list` for the list.

**Comment by yitongshang2021** [comment]
Thanks @stefanhgm, it work for us!
