### ISSUE TITLE
How to make the T0_11B model into multi-GPU?

### ISSUE THREAD

**Issue by yitongshang2021** [clinicalml/TabLLM#33]
Hi, I want to ask How to make the T0_11B model into multi-GPU?
Because I have meet the follow error of out of memory
RuntimeError: CUDA out of memory. Tried to allocate 80.00 MiB (GPU 0; 79.14 GiB total capacity; 76.67 GiB already allocated; 48.75 MiB free; 76.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Please give me some insight if you convience, thanks!

**Comment by stefanhgm** [comment]
Hi @yitongshang2021 

as answered in #32, we ran TabLLM on a single GPU setup with a A100 80GB. Please check the pointer I have given in this thread if you can make it run.

Best
Stefan
